// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23GMc5DcOSuibZNsBD7Soyj8r8Z8I4NU',
    appId: '1:708931486690:web:020638cdc36ca2ef582fbb',
    messagingSenderId: '708931486690',
    projectId: 'flutter-chat-app-5a50b',
    authDomain: 'flutter-chat-app-5a50b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5a50b.appspot.com',
    measurementId: 'G-9EKJSW07X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-aFps9aRWs3BICYk3prBm9mzqdA3QB1c',
    appId: '1:708931486690:android:c2a0c9e0ef7653eb582fbb',
    messagingSenderId: '708931486690',
    projectId: 'flutter-chat-app-5a50b',
    storageBucket: 'flutter-chat-app-5a50b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0icCr2FbslejbcU4zPQ0bclsEOWOsZ0',
    appId: '1:708931486690:ios:7ae5d52b8ee5bf44582fbb',
    messagingSenderId: '708931486690',
    projectId: 'flutter-chat-app-5a50b',
    storageBucket: 'flutter-chat-app-5a50b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0icCr2FbslejbcU4zPQ0bclsEOWOsZ0',
    appId: '1:708931486690:ios:8bb55b13146f83fc582fbb',
    messagingSenderId: '708931486690',
    projectId: 'flutter-chat-app-5a50b',
    storageBucket: 'flutter-chat-app-5a50b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
